### ISSUE TITLE
Enable multiple wireguard connections

### ISSUE THREAD

**Issue by whoisnobody** [SJBERTRAND/gnome-wireguard-extension#11]
Hi, 
Is there any possibility to enable more than one wireguard connection at the same time? At the moment I receive an error when trying to enable other wg connection without closing the first one.

**Comment by SJBERTRAND** [comment]
It shouldn't be a problem as the extension itself only send signal to network manager to activate/deactivate connection and monitor active/inactive connection. The problem might be within your wireguard tunnels configuration files.  Every tunnel has a connection name and an interface name. The interface name cannot be the same. The interface name is often named wg0. If you have two tunnels that have wg0 as an interface name you will only be able to used one a the time. (I think this is most likely the problem here).
